_BASE_RUN: ../../../pool/run/training/from_scratch.yaml
_BASE_MODEL: ../../../pool/backbone/tsm.yaml

PRETRAIN:
  ENABLE: true
  NUM_CLIPS_PER_VIDEO: 2
  GENERATOR: ContrastiveGenerator
  LOSS: PROTOTYPE
  DEBUG: false
  LOSS_WEIGHTS: [1]
  CONTRASTIVE:
    TEMPERATURE: 0.2
    DROPOUT: 0.0
    SYMMETRIC: false
    LABEL_SMOOTH_FACTOR: 0.0
    THRE: true
    THRE_1: 0.7
    THRE_2: 0.7
    MIXUP: false
    MIX_P: 0.025
    MIX_ALPHA: 1
    SHUFFLE: true
    SHUFFLE_P: 1
    DUPLICATE: false
    DUPLICATE_P: 0.5
TRAIN:
  ENABLE: true
  DATASET: UCF101
  BATCH_SIZE: 32
  OPENSET: true
  EVAL_PERIOD: 50
  CHECKPOINT_PERIOD: 50
  NUM_FOLDS: 50
TEST:
  ENABLE: true
  DATASET: UCF101
  BATCH_SIZE: 16
  ENABLE_OPEN: true
  OPEN_METHOD: maha_distance
  DATASET_IN: UCF101
  DATASET_OOD: HMDB51
  RESULT_FILE_NAME: "tsm_maha_distance.npz"
  AUTOMATIC_MULTI_SCALE_TEST: false
DATA:
  DATA_ROOT_DIR: ""
  ANNO_DIR: ""
  TRAIN_CROP_SIZE: 224
  TEST_SCALE: 224
  TEST_CROP_SIZE: 224
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 8
  SAMPLING_MODE: segment_based
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
DATA_IN:
  DATA_ROOT_DIR: ""
  ANNO_DIR: ""
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 8
  SAMPLING_MODE: segment_based
  NUM_INPUT_CHANNELS: 3
  TEST_SCALE: 224
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  MULTI_LABEL: false
  SPLIT_ID: 1
  ENSEMBLE_METHOD: sum
  FPS: 30
  TARGET_FPS: 30
DATA_OOD:
  DATA_ROOT_DIR: ""
  ANNO_DIR: ""
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 8
  SAMPLING_MODE: segment_based
  NUM_INPUT_CHANNELS: 3
  TEST_SCALE: 224
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  MULTI_LABEL: false
  SPLIT_ID: 1
  ENSEMBLE_METHOD: sum
  FPS: 30
  TARGET_FPS: 30
OPTIMIZER:
  BASE_LR: 0.6
  LR_POLICY: cosine
  MAX_EPOCH: 400
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-6
  WARMUP_EPOCHS: 5
  WARMUP_START_LR: 0.001
  OPTIM_METHOD: lars
  DAMPENING: 0.0
  NESTEROV: true
  BN_LARS_EXCLUDE: true
  ADJUST_LR: true
VIDEO:
  HEAD:
    NAME: VideoMLPHead
    ACTIVATION: 
    DROPOUT_RATE: 0
    NUM_CLASSES: 101              # !!!
    MLP:
      MID_DIM: 1024
      OUT_DIM: 128
      MID_BN: true
      FINAL_BN: false
PRE_DOWNLOAD:
  ENABLE: false
MODEL:
  NAME: PrototypeModel
  NUM_CLASSES: 101
  LEARNABLE_PROTOTYPE: true
  SYNC_BN: true
  MLP: true

AUGMENTATION:
  BRIGHTNESS: 0.8
  CONTRAST: 0.8
  SATURATION: 0.8
  HUE: 0.2
  GRAYSCALE: 0.2
  COLOR: 0.8
  CONSISTENT: true
  SHUFFLE: true
  RATIO: [1, 1]
  USE_GPU: false

BN:
  SYNC_BN: true
